--CREATE PROCEDURE [dbo].[RegisterGestionnaire]
--	@prenom VARCHAR(50),
--	@nom VARCHAR(50),
--	@email VARCHAR(100),
--	@telephone VARCHAR(15),
--	@id_utilisateur INT
--AS
--BEGIN
--	INSERT INTO Gestionnaire (prenom, nom, email, telephone, id_utilisateur)
--	VALUES ()
--END
